name: notion-financial-status

services:
  financial-status:
    image: pmarzoa/notion-financial-status:latest
    container_name: financial-status
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - PORT=8080
    labels:
      icon: "https://raw.githubusercontent.com/PabloMarzoa/notion-financial-status/master/public/favicon.ico"
